%YAML:1.0

imu0:
  T_i_b:
    - [1.0, 0.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0, 0.0]
    - [0.0, 0.0, 0.0, 1.0]
  accelerometer_noise_density: 2.28e-02
  accelerometer_random_walk: 9.16e-04
  gyroscope_noise_density: 1.87e-04 
  gyroscope_random_walk: 7.71e-07 
  model: calibrated
  rostopic: /mavros/imu/full
  time_offset: 0.0038413192268401297
  update_rate: 150.0
